# Generated by Django 2.2.4 on 2019-08-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('subject_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('ia_marks', models.IntegerField()),
                ('exam_marks', models.IntegerField()),
                ('total_no_lecture_hours', models.IntegerField()),
                ('total_no_lecture_hours_per_week', models.IntegerField()),
                ('exam_hours', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('sem', models.CharField(choices=[('I', '1'), ('II', '2'), ('III', 3), ('IV', 4), ('V', '5'), ('VI', '6'), ('VII', '7'), ('VIII', '8')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('courses_taken', models.ManyToManyField(related_name='students', to='core.Course')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
