# Generated by Django 2.2.4 on 2019-08-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Computer Science', 'CS'), ('Electronics And Communication', 'ENC'), ('Civil', 'CV'), ('Mechanical', 'ME')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='program_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program'),
        ),
    ]
